# Generated by Django 6.1 on 2026-09-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='sellerprofile',
            options={'ordering': ['-created_at']},
        ),
    ]
