# Generated by Django 6.1 on 2026-09-29 19:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customerprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='balance',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='customers/avatars/'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver_name', models.CharField(help_text='Name of the person receiving the package', max_length=150)),
                ('receiver_phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: +989XXXXXXXXX', regex='^\\+989\\d{9}$')])),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address_line', models.CharField(max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
            },
        ),
    ]
