# Generated by Django 6.1 on 2026-09-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
