# Generated by Django 6.1 on 2026-09-28 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name_plural': 'heroes'},
        ),
    ]
